name: Go presubmit

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Go presubmit
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ['stable']
        os: ['ubuntu-latest']
    steps:
    - uses: actions/checkout@v3
    - name: Install Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
    - uses: creachadair/go-presubmit-action@84681112a41e5715b1c78662e09db1552549beb1
      with:
        check-replace: 'false'
